import mongoose, { Document, Schema } from "mongoose";

/**
 * @swagger
 * components:
 *   schemas:
 *     Notification:
 *       type: object
 *       description: An in-app notification generated by the alert job.
 *       properties:
 *         _id:
 *           type: string
 *           description: Unique identifier of the notification.
 *           example: 60d0fe4f5311236168a109ca
 *         userId:
 *           type: string
 *           description: ID of the recipient user.
 *           example: 60d0fe4f5311236168a109cb
 *         type:
 *           type: string
 *           enum: [new_match, price_drop, status_change]
 *           description: The event category that triggered this notification.
 *           example: new_match
 *         title:
 *           type: string
 *           description: Short notification title shown in the notification center.
 *           example: "New listing matches your search"
 *         body:
 *           type: string
 *           description: Longer description of the event.
 *           example: "3 new properties match \"2BR Chapel Hill\" since your last check."
 *         metadata:
 *           type: object
 *           description: Structured event context (zpids, old/new price, searchId, etc.).
 *         isRead:
 *           type: boolean
 *           description: Whether the user has read this notification.
 *           default: false
 *         eventKey:
 *           type: string
 *           description: Deterministic idempotency key so duplicate events are not emitted.
 *           example: "savedSearch_abc123_new_match_2024-01-15"
 *         createdAt:
 *           type: string
 *           format: date-time
 *       required:
 *         - userId
 *         - type
 *         - title
 *         - body
 *         - eventKey
 */

export interface INotification extends Document {
  userId: mongoose.Types.ObjectId;
  type: "new_match" | "price_drop" | "status_change";
  title: string;
  body: string;
  metadata?: Record<string, unknown>;
  isRead: boolean;
  eventKey: string;
  createdAt: Date;
}

const NotificationSchema: Schema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    type: {
      type: String,
      enum: ["new_match", "price_drop", "status_change"],
      required: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    body: {
      type: String,
      required: true,
      trim: true,
    },
    metadata: {
      type: Schema.Types.Mixed,
      default: {},
    },
    isRead: {
      type: Boolean,
      default: false,
      index: true,
    },
    eventKey: {
      type: String,
      required: true,
      unique: true,
    },
  },
  { timestamps: true },
);

// Index for quick unread-count lookups
NotificationSchema.index({ userId: 1, isRead: 1, createdAt: -1 });

export default mongoose.model<INotification>(
  "Notification",
  NotificationSchema,
);
